version: 2.1
jobs:
  build:
    docker:
      - image: archlinux/base
    steps:
      - checkout
      - run: |
          pacman -Syuq --noconfirm git base-devel
          useradd user
          echo "user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/user
          chown -R user /root
          for x in */PKGBUILD
          do [ -r "$x" ] && (
            cd "${x%/*}"
            sudo -u user makepkg -s --noconfirm
          ) done
